### ISSUE TITLE
this is very pog

### ISSUE THREAD

**Issue by Parapass** [Slied1961/ModAssistantPatched#1]
you are very Pog for helping idiots who wont bother to pay a cent for actually good games get their open-source mod installers patched because you feel like you're entitled to free games, meanwhile you're out here spending 400 dollars on headsets with sensors on them. So yes, this is pretty Pog.

**Comment by Slied1961** [comment]
its an open source application adding anti piracy code not to mention the whole beat saber community pirates songs so whats your whole argument here not everyone is innocent neither is yourself nice to see you support the artist (https://www.youtube.com/watch?v=JCGr-ryiLsY) /s
